name: map-downloader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests
  - pathlib
  - pillow
  - pip
  - pip:
    - pyinstaller>=5.0
    - tkinter-tooltip
platforms:
  - osx-64
  - osx-arm64
  - win-64
  - linux-64